version: "3.7"

networks:
  common:
    external: true     

services:
  caddy:
    image: caddy:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${STORAGE}/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${STORAGE}/config/caddy/site:/srv
      - ${STORAGE}/data/caddy-data/data:/data
      - ${STORAGE}/data/caddy-data/config:/config
    networks:
      - common

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: "unless-stopped"
    ports:
     - "8096:8096"
    volumes:
      - ${STORAGE}/config/jellyfin/config:/config
      - ${STORAGE}/data/jellyfin-data/cache:/cache
      - ${STORAGE}/data/media/movies:/movies
      - ${STORAGE}/data/media/tv-shows:/tv-shows
    networks:
      - common

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=admin #optional
      - PASS=admin #optional
    volumes:
      - /c/Users/j/Documents/Media-Center/transmission/config:/config
      - /c/Users/j/Documents/Media-Center/transmission/downloads:/downloads
      - /c/Users/j/Documents/Media-Center/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - common
  
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=197609
      - PGID=197121
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /c/Users/j/Documents/Media-Center/jackett:/config
      - /c/Users/j/Documents/Media-Center/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - common

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=197609
      - PGID=197121
      - TZ=Europe/Madrid
    volumes:
      - /c/Users/j/Documents/Media-Center/sonarr/data:/config
      - /c/Users/j/Documents/Media-Center/sonarr/tvseries:/tv #optional
      - /c/Users/j/Documents/Media-Center/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - common
